## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  # - nightly
  # - release
notifications:
  email: false
matrix:
  allow_failures:
     - julia: nightly 
script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("EmpiricalRiskMinimization",coverage=true)'
after_success:
  - julia -e julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("EmpiricalRiskMinimization")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("EmpiricalRiskMinimization")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("EmpiricalRiskMinimization")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
